import {fetchSingleCat} from "../../../src/server/fetchWikiApi"
import {debug, log} from "../../../src/utils"
import Moralis from "moralis/node"
import {moralisSetup} from "../../../src/baseApi"

export async function createItem(name: string, isPerson: boolean, wikitext?: string, img?: string, category?: string) {
    moralisSetup(false, Moralis)

    const WikiPerson = Moralis.Object.extend("WikiPerson")
    const WikiObject = Moralis.Object.extend("WikiObject")
    const classObj = isPerson ? WikiPerson : WikiObject
    const query = new Moralis.Query(classObj)
    query.equalTo("name", name)

    const results = await query.find()
    debug("results", results)
    if (results.length === 0) {
        const item = isPerson ? new WikiPerson() : new WikiObject()

        item.set("name", name)
        if (wikitext || img || category)
            item.set("data", {wikitext, img, category})

        try {
            await item.save()
            debug("ok, saved ", name, ": ", item)
        } catch (error) {
            // Show the error message somewhere and let the user try again.
            log("Error: " + error.code + " " + error.message)
        }
    }
}

export default async (req, res) => {
    const id = decodeURIComponent(req.url.substring(req.url.lastIndexOf("/") + 1))
    const arr = []
    const d =
        decades.find(x => x.replace("s", "").includes(":" + id + " ")) ||
        (id.includes("Category:") && id.includes("births")) ? id : ""

    const whenDone = () => {
        debug("done decade <" + d + ">", arr)
        res.status(200).json(arr)
    }
    const whenError = (error) => {
        debug("error with decade <" + d + ">", arr)
        res.status(200).json([])
    }
    const withCat = name => {
        debug("cat for decade <" + d + ">", name)
        arr.push({category: true, name})
    }
    const withItem = name => {
        debug("item for decade <" + d + ">", name)
        arr.push({category: false, name})
        createItem(name, true)
    }
    debug("researching decade <" + d + ">")
    await fetchSingleCat(d, withCat, withItem, whenDone, whenError)
}

const decades = [
    "Category:0s BC births",
    "Category:10s BC births",
    "Category:20s BC births",
    "Category:30s BC births",
    "Category:40s BC births",
    "Category:50s BC births",
    "Category:60s BC births",
    "Category:70s BC births",
    "Category:80s BC births",
    "Category:90s BC births",
    "Category:100s BC births",
    "Category:110s BC births",
    "Category:120s BC births",
    "Category:130s BC births",
    "Category:140s BC births",
    "Category:150s BC births",
    "Category:160s BC births",
    "Category:170s BC births",
    "Category:180s BC births",
    "Category:190s BC births",
    "Category:200s BC births",
    "Category:210s BC births",
    "Category:220s BC births",
    "Category:230s BC births",
    "Category:240s BC births",
    "Category:250s BC births",
    "Category:260s BC births",
    "Category:270s BC births",
    "Category:280s BC births",
    "Category:290s BC births",
    "Category:300s BC births",
    "Category:310s BC births",
    "Category:320s BC births",
    "Category:330s BC births",
    "Category:340s BC births",
    "Category:350s BC births",
    "Category:360s BC births",
    "Category:370s BC births",
    "Category:380s BC births",
    "Category:390s BC births",
    "Category:400s BC births",
    "Category:410s BC births",
    "Category:420s BC births",
    "Category:430s BC births",
    "Category:440s BC births",
    "Category:450s BC births",
    "Category:460s BC births",
    "Category:470s BC births",
    "Category:480s BC births",
    "Category:490s BC births",
    "Category:500s BC births",
    "Category:510s BC births",
    "Category:520s BC births",
    "Category:530s BC births",
    "Category:540s BC births",
    "Category:550s BC births",
    "Category:560s BC births",
    "Category:570s BC births",
    "Category:580s BC births",
    "Category:600s BC births",
    "Category:610s BC births",
    "Category:620s BC births",
    "Category:630s BC births",
    "Category:640s BC births",
    "Category:650s BC births",
    "Category:660s BC births",
    "Category:670s BC births",
    "Category:680s BC births",
    "Category:690s BC births",
    "Category:700s BC births",
    "Category:710s BC births",
    "Category:720s BC births",
    "Category:730s BC births",
    "Category:740s BC births",
    "Category:750s BC births",
    "Category:790s BC births",
    "Category:800s BC births",
    "Category:840s BC births",
    "Category:860s BC births",
    "Category:870s BC births",
    "Category:880s BC births",
    "Category:910s BC births",
    "Category:920s BC births",
    "Category:930s BC births",
    "Category:940s BC births",
    "Category:950s BC births",
    "Category:970s BC births",
    "Category:1000s BC births",
    "Category:1050s BC births",
    "Category:1060s BC births",
    "Category:1150s BC births",
    "Category:1300s BC births",
    "Category:1340s BC births",
    "Category:1360s BC births",
    "Category:1390s BC births",
    "Category:0s births",
    "Category:10s births",
    "Category:20s births",
    "Category:30s births",
    "Category:40s births",
    "Category:50s births",
    "Category:60s births",
    "Category:70s births",
    "Category:80s births",
    "Category:90s births",
    "Category:100s births",
    "Category:110s births",
    "Category:120s births",
    "Category:130s births",
    "Category:140s births",
    "Category:150s births",
    "Category:160s births",
    "Category:170s births",
    "Category:180s births",
    "Category:190s births",
    "Category:200s births",
    "Category:210s births",
    "Category:220s births",
    "Category:230s births",
    "Category:240s births",
    "Category:250s births",
    "Category:260s births",
    "Category:270s births",
    "Category:280s births",
    "Category:290s births",
    "Category:300s births",
    "Category:310s births",
    "Category:320s births",
    "Category:330s births",
    "Category:340s births",
    "Category:350s births",
    "Category:360s births",
    "Category:370s births",
    "Category:380s births",
    "Category:390s births",
    "Category:400s births",
    "Category:410s births",
    "Category:420s births",
    "Category:430s births",
    "Category:440s births",
    "Category:450s births",
    "Category:460s births",
    "Category:470s births",
    "Category:480s births",
    "Category:490s births",
    "Category:500s births",
    "Category:510s births",
    "Category:520s births",
    "Category:530s births",
    "Category:540s births",
    "Category:550s births",
    "Category:560s births",
    "Category:570s births",
    "Category:580s births",
    "Category:590s births",
    "Category:600s births",
    "Category:610s births",
    "Category:620s births",
    "Category:630s births",
    "Category:640s births",
    "Category:650s births",
    "Category:660s births",
    "Category:670s births",
    "Category:680s births",
    "Category:690s births",
    "Category:700s births",
    "Category:710s births",
    "Category:720s births",
    "Category:730s births",
    "Category:740s births",
    "Category:750s births",
    "Category:760s births",
    "Category:770s births",
    "Category:780s births",
    "Category:790s births",
    "Category:800s births",
    "Category:810s births",
    "Category:820s births",
    "Category:830s births",
    "Category:840s births",
    "Category:850s births",
    "Category:860s births",
    "Category:870s births",
    "Category:880s births",
    "Category:890s births",
    "Category:900s births",
    "Category:910s births",
    "Category:920s births",
    "Category:930s births",
    "Category:940s births",
    "Category:950s births",
    "Category:960s births",
    "Category:970s births",
    "Category:980s births",
    "Category:990s births",
    "Category:1000s births",
    "Category:1010s births",
    "Category:1020s births",
    "Category:1030s births",
    "Category:1040s births",
    "Category:1050s births",
    "Category:1060s births",
    "Category:1070s births",
    "Category:1080s births",
    "Category:1090s births",
    "Category:1100s births",
    "Category:1110s births",
    "Category:1120s births",
    "Category:1130s births",
    "Category:1140s births",
    "Category:1150s births",
    "Category:1160s births",
    "Category:1170s births",
    "Category:1180s births",
    "Category:1190s births",
    "Category:1200s births",
    "Category:1210s births",
    "Category:1220s births",
    "Category:1230s births",
    "Category:1240s births",
    "Category:1250s births",
    "Category:1260s births",
    "Category:1270s births",
    "Category:1280s births",
    "Category:1290s births",
    "Category:1300s births",
    "Category:1310s births",
    "Category:1320s births",
    "Category:1330s births",
    "Category:1340s births",
    "Category:1350s births",
    "Category:1360s births",
    "Category:1370s births",
    "Category:1380s births",
    "Category:1390s births",
    "Category:1400s births",
    "Category:1410s births",
    "Category:1420s births",
    "Category:1430s births",
    "Category:1440s births",
    "Category:1450s births",
    "Category:1460s births",
    "Category:1470s births",
    "Category:1480s births",
    "Category:1490s births",
    "Category:1500s births",
    "Category:1510s births",
    "Category:1520s births",
    "Category:1530s births",
    "Category:1540s births",
    "Category:1550s births",
    "Category:1560s births",
    "Category:1570s births",
    "Category:1580s births",
    "Category:1590s births",
    "Category:1600s births",
    "Category:1610s births",
    "Category:1620s births",
    "Category:1630s births",
    "Category:1640s births",
    "Category:1650s births",
    "Category:1660s births",
    "Category:1670s births",
    "Category:1680s births",
    "Category:1690s births",
    "Category:1700s births",
    "Category:1710s births",
    "Category:1720s births",
    "Category:1730s births",
    "Category:1740s births",
    "Category:1750s births",
    "Category:1760s births",
    "Category:1770s births",
    "Category:1780s births",
    "Category:1790s births",
    "Category:1800s births",
    "Category:1810s births",
    "Category:1820s births",
    "Category:1830s births",
    "Category:1840s births",
    "Category:1850s births",
    "Category:1860s births",
    "Category:1870s births",
    "Category:1880s births",
    "Category:1890s births",
    "Category:1900s births",
    "Category:1910s births",
    "Category:1920s births",
    "Category:1930s births",
    "Category:1940s births",
    "Category:1950s births",
    "Category:1960s births",
    "Category:1970s births",
    "Category:1980s births",
    "Category:1990s births",
    "Category:2000s births",
    "Category:2010s births",
    "Category:2020s births"
]
